import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { userInfo } from 'node:os';
import {
  daemonLogDir,
  daemonStderrPath,
  daemonStdoutPath,
  windowsHiddenWrapperPath,
  windowsLauncherCmdPath,
  windowsTaskName,
  windowsTaskXmlPath,
} from './paths';
import { paths } from '../config/paths';

export interface LauncherInputs {
  /** Absolute path to node.exe. */
  nodePath: string;
  /** Absolute path to the bridge CLI entry. */
  bridgeEntryPath: string;
  /** PATH for the child process; baked into the .cmd via `set PATH=`. */
  envPath: string;
  /** Service id (profile name, or the reserved supervisor id) — drives the
   * task name and log paths. */
  profile: string;
  /** CLI args after the entry path, e.g. `['run', '--profile', 'claude']` or
   * `['run', '--web-ui']`. */
  runArgs: string[];
  /** Root directory for config/profile state. */
  channelHome: string;
}

/**
 * Generate the .cmd wrapper script that the scheduled task actually invokes.
 *
 * schtasks `/TR` can accept a direct command, but we need stdout/stderr
 * redirection + a PATH override so child tools (lark-cli, claude) resolve
 * correctly when the daemon runs under Task Scheduler. A `.cmd` script
 * is the natural place for both.
 *
 * `@echo off` keeps the script's own commands out of the daemon log.
 * `>>` / `2>>` append (not truncate) so log history is preserved across
 * daemon restarts.
 */
export function buildLauncherCmd(inputs: LauncherInputs): string {
  // Profile names / flags are validated safe tokens (no spaces).
  const runArgs = inputs.runArgs.join(' ');
  return [
    '@echo off',
    `set "LARK_CHANNEL_HOME=${inputs.channelHome}"`,
    `set "PATH=${inputs.envPath}"`,
    `"${inputs.nodePath}" "${inputs.bridgeEntryPath}" ${runArgs} >> "${daemonStdoutPath(inputs.profile)}" 2>> "${daemonStderrPath(inputs.profile)}"`,
    '',
  ].join('\r\n');
}

async function writeLauncherCmd(profile: string, runArgs: string[] = ['run']): Promise<string> {
  const bridgeEntryPath = process.argv[1];
  if (!bridgeEntryPath) {
    throw new Error('cannot determine bridge entry path (process.argv[1] is empty)');
  }
  const content = buildLauncherCmd({
    nodePath: process.execPath,
    bridgeEntryPath,
    envPath: process.env.PATH ?? '',
    profile,
    runArgs,
    channelHome: paths.rootDir,
  });
  const cmdPath = windowsLauncherCmdPath(profile);
  await mkdir(dirname(cmdPath), { recursive: true });
  await mkdir(daemonLogDir(profile), { recursive: true });
  await writeFile(cmdPath, content, 'utf8');
  return cmdPath;
}

/**
 * VBS wrapper that runs the launcher .cmd with a hidden window and waits for
 * it. `bWaitOnReturn = True` matters: if the wrapper exited immediately, Task
 * Scheduler would consider the task instance finished the moment the daemon
 * was spawned, which would break `schtasks /Query` running-state detection.
 *
 * The daemon's exit code is propagated so an unexpected death is recorded as a
 * failed task action — that is what makes `RestartOnFailure` in the task XML
 * actually fire. A launcher that cannot be started at all has no exit code to
 * report and is likewise reported as a failure, rather than passing silently.
 */
export function buildHiddenWrapperVbs(cmdPath: string): string {
  return [
    "' Auto-generated by lark-channel-bridge. Do not edit.",
    "' Runs the daemon launcher with no visible console window, so the window",
    "' cannot be closed by accident (that kills the daemon with 0xC000013A).",
    'Set sh = CreateObject("WScript.Shell")',
    "' Fail loudly when the launcher cannot be started at all: there is no exit",
    "' code to report, and letting the script die quietly would mark the task",
    "' successful while no daemon runs — nothing would ever retry it.",
    'On Error Resume Next',
    `code = sh.Run("""${cmdPath}""", 0, True)`,
    'If Err.Number <> 0 Then WScript.Quit 1',
    'On Error GoTo 0',
    "' Propagate the daemon's own exit code so a non-zero exit is recorded as a",
    "' failed action (keeping 0xC000013A readable in the task's Last Result),",
    "' which is what makes RestartOnFailure fire.",
    'WScript.Quit code',
    '',
  ].join('\r\n');
}

/**
 * Encode the wrapper the way Windows Script Host expects to read it.
 *
 * WSH only honours UTF-16LE with a BOM for non-ASCII scripts; a UTF-8 file is
 * decoded with the ANSI code page instead, so any non-ASCII path baked into
 * the wrapper turns into mojibake and `sh.Run` never launches the daemon. That
 * affects the common case of a Windows account whose name is not ASCII
 * (`C:\Users\<non-ASCII>\.lark-channel\...`), where the profile path is
 * non-ASCII even though the wrapper's own contents are not.
 */
export function encodeHiddenWrapperVbs(vbs: string): Buffer {
  return Buffer.concat([Buffer.from([0xff, 0xfe]), Buffer.from(vbs, 'utf16le')]);
}

export interface TaskXmlInputs {
  /** Registered task name, e.g. `LarkChannelBridge.Bot.dsh`. */
  taskName: string;
  /** Hidden wrapper (.vbs) the task executes. */
  wrapperPath: string;
  /** Account the task runs as, e.g. `MACHINE\user`. */
  userId: string;
}

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Build the Task Scheduler XML for the daemon task.
 *
 * Differences from a plain `schtasks /Create /SC ONLOGON`, each one closing a
 * way the daemon can silently disappear:
 *  - `DisallowStartIfOnBatteries` / `StopIfGoingOnBatteries` = false — on a
 *    laptop the defaults refuse to autostart on battery and *kill* the daemon
 *    when the charger is unplugged.
 *  - `ExecutionTimeLimit` = PT0S — the 72h default hard-terminates a daemon
 *    that is meant to run forever.
 *  - `RestartOnFailure` — an unexpected exit is retried a minute later
 *    instead of waiting for the next logon.
 *  - `StartWhenAvailable` = true — a missed logon trigger still runs.
 *  - action = `wscript.exe <hidden wrapper>` — no console window to close.
 */
export function buildTaskXml(inputs: TaskXmlInputs): string {
  const task = xmlEscape(inputs.taskName);
  const user = xmlEscape(inputs.userId);
  const wrapper = xmlEscape(inputs.wrapperPath);
  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Author>${user}</Author>
    <Description>lark-channel-bridge daemon (${task})</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>${user}</UserId>
      <Delay>PT15S</Delay>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>${user}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>999</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>wscript.exe</Command>
      <Arguments>//nologo "${wrapper}"</Arguments>
    </Exec>
  </Actions>
</Task>
`;
}

/**
 * Candidate account ids for the task principal/trigger, most specific first.
 * `schtasks /Create /XML` rejects the whole file on an unresolvable account,
 * so we retry with the bare user name when the domain-qualified form fails.
 */
function userIdCandidates(): string[] {
  const name = userInfo().username || process.env.USERNAME || '';
  const domain = process.env.USERDOMAIN ?? '';
  const candidates = [domain && name ? `${domain}\\${name}` : '', name].filter(Boolean);
  return [...new Set(candidates)];
}

interface SchtasksResult {
  ok: boolean;
  stderr: string;
  stdout: string;
}

function runSchtasks(args: string[]): SchtasksResult {
  const r = spawnSync('schtasks', args, { encoding: 'utf8' });
  return {
    ok: r.status === 0,
    stderr: r.stderr ?? '',
    stdout: r.stdout ?? '',
  };
}

/**
 * Create (or overwrite) the scheduled task from XML.
 *
 * The XML route is required for the settings that keep a laptop daemon alive
 * (battery flags, no execution time limit, restart-on-failure, hidden-window
 * action) — `schtasks /Create` has no switches for any of them. `/RL LIMITED`
 * is expressed as `<RunLevel>LeastPrivilege</RunLevel>`, and the logon trigger
 * as `<LogonTrigger>`, so no elevation is needed for the current user.
 */
export async function installTask(
  profile: string,
  runArgs: string[] = ['run'],
): Promise<SchtasksResult> {
  const cmdPath = await writeLauncherCmd(profile, runArgs);
  const wrapperPath = windowsHiddenWrapperPath(profile);
  // Both artifacts live in the same directory as the launcher, but create it
  // here too rather than relying on writeLauncherCmd's side effect.
  await mkdir(dirname(wrapperPath), { recursive: true });
  await writeFile(wrapperPath, encodeHiddenWrapperVbs(buildHiddenWrapperVbs(cmdPath)));

  const xmlPath = windowsTaskXmlPath(profile);
  const taskName = windowsTaskName(profile);
  let last: SchtasksResult = { ok: false, stderr: 'no account candidate for task principal', stdout: '' };
  for (const userId of userIdCandidates()) {
    const xml = buildTaskXml({ taskName, wrapperPath, userId });
    // Task Scheduler expects Unicode XML; write UTF-16LE with a BOM.
    await writeFile(xmlPath, Buffer.concat([Buffer.from([0xff, 0xfe]), Buffer.from(xml, 'utf16le')]));
    last = runSchtasks(['/Create', '/F', '/TN', taskName, '/XML', xmlPath]);
    if (last.ok) return last;
  }
  return last;
}

/** Start the task now (regardless of trigger). */
export function runTask(profile: string): SchtasksResult {
  return runSchtasks(['/Run', '/TN', windowsTaskName(profile)]);
}

/** End the running instance. Task stays registered for next logon. */
export function endTask(profile: string): SchtasksResult {
  return runSchtasks(['/End', '/TN', windowsTaskName(profile)]);
}

/** Disable autostart (task stays registered but ONLOGON trigger won't fire). */
export function disableTask(profile: string): SchtasksResult {
  return runSchtasks(['/Change', '/TN', windowsTaskName(profile), '/Disable']);
}

/** Re-enable autostart. Called from installTask is unnecessary — /Create /F
 * resets the enabled flag. Only needed if you Disabled and want it back. */
export function enableTask(profile: string): SchtasksResult {
  return runSchtasks(['/Change', '/TN', windowsTaskName(profile), '/Enable']);
}

/** End + disable. The cross-platform "stop = stay stopped" semantic. */
export function endAndDisable(profile: string): SchtasksResult {
  const ended = endTask(profile);
  // If the task wasn't running, /End fails; we still want to disable.
  const disabled = disableTask(profile);
  // Surface whichever signal is more informative — disable result wins
  // because the autostart prevention is the user-visible effect.
  return disabled.ok ? disabled : ended.ok ? disabled : ended;
}

/** Schtasks has no native restart — end, wait, run. */
export async function restartTask(profile: string): Promise<SchtasksResult> {
  endTask(profile); // best-effort; ignore if not running
  await waitUntilStopped(profile);
  return runTask(profile);
}

/**
 * `schtasks /Query` returns 0 iff the task is registered. We toss the
 * output (it's verbose); use describeTask for full state.
 */
export function isTaskRegistered(profile: string): boolean {
  const r = spawnSync('schtasks', ['/Query', '/TN', windowsTaskName(profile)], {
    stdio: ['ignore', 'ignore', 'ignore'],
  });
  return r.status === 0;
}

/**
 * Parse `/Query /V /FO LIST` output for the current run state. Looks for
 * `Status: Running` in the verbose listing. Other states include
 * "Ready" (registered, not currently running) and "Disabled".
 */
export function isTaskRunning(profile: string): boolean {
  const r = runSchtasks(['/Query', '/V', '/FO', 'LIST', '/TN', windowsTaskName(profile)]);
  if (!r.ok) return false;
  return /Status:\s+Running/i.test(r.stdout);
}

export function describeTask(profile: string): string {
  const r = runSchtasks(['/Query', '/V', '/FO', 'LIST', '/TN', windowsTaskName(profile)]);
  return r.stdout || r.stderr || '';
}

export async function waitUntilStopped(profile: string, timeoutMs = 5000): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (!isTaskRunning(profile)) return true;
    await new Promise((r) => setTimeout(r, 200));
  }
  return false;
}

export async function deleteTask(profile: string): Promise<SchtasksResult> {
  const r = runSchtasks(['/Delete', '/F', '/TN', windowsTaskName(profile)]);
  // Remove the generated launcher/wrapper/XML too; best-effort.
  for (const file of [
    windowsLauncherCmdPath(profile),
    windowsHiddenWrapperPath(profile),
    windowsTaskXmlPath(profile),
  ]) {
    if (existsSync(file)) {
      await rm(file, { force: true });
    }
  }
  return r;
}
